# warnings

# runners
warnings: false
n_jobs: 1
n_hyperparam_folds: 3

cox_tol_evo: 0.0000001
cox_downsample_alpha_evo: false
pretune_coxnet_alpha_evo: true

verbose_evo: true
pop_size_evo: 512
max_gen_evo: 50
early_stopping_rounds_evo: 5
max_tree_size_evo: 7
init_max_depth_evo: 2

drop_features_evo: true
only_generated_evo: false
only_numerical_features_evo: false
inner_val_size_evo: 0.0

n_sequential_rounds_evo: 1

prob_init_tree_evo: 0.05
prob_delete_tree_evo: 0.05
prob_mt_crossover_evo: 0.0
min_trees_init_evo: 2
max_trees_init_evo: 5

# experiment
seed: 42
n_replicates: 30
corrdrop_threshold: 0.98
test_size: 0.1
scale_numerical: false
metric: "cindex" # cindex, cindex_ipcw or mean_auc